name: 04 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checout@v4
          - name: Printing Folders
            run: ls
    # checkout code from repo

    # install deps of react